### ISSUE TITLE
📝 パフォーマンス改善: フォント読み込みの最適化

### ISSUE THREAD

**Issue by ryota-09** [ryota-09/ryota-blog#68]
## 概要
Webフォントの読み込みがレンダリングに影響を与えている可能性があります。フォント読み込み戦略を最適化する必要があります。

## 問題点
- フォント読み込み中のテキスト表示遅延
- FOIT (Flash of Invisible Text) の可能性
- フォントファイルの最適化不足

### 1. font-display: swap の適用
```css
@font-face {
  font-family: 'YourFont';
  src: url('/fonts/your-font.woff2') format('woff2');
  font-display: swap; /* 重要 */
}
```

### 2. 重要フォントのpreload
```html
<link rel="preload" href="/fonts/primary-font.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
```

### 3. Google Fontsの最適化（使用している場合）
```html
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet" />
```

### 4. フォントファイルの最適化
- WOFF2フォーマットの使用
- 不要な文字セットの削除
- フォントサブセット化

### 5. システムフォントのフォールバック
```css
font-family: 'YourFont', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
```

## 調査項目
1. 現在使用中のフォント確認
2. フォント読み込み方法の確認
3. FOIT/FOUT の有無確認

## 受け入れ基準
- [ ] すべてのWebフォントに`font-display: swap`が設定されていること
- [ ] 重要フォントがpreloadされていること
- [ ] フォント読み込み中もテキストが表示されること
- [ ] CLS (Cumulative Layout Shift) が発生しないこと
- [ ] フォント読み込みパフォーマンスが改善されること

## 優先度
中（UX改善とパフォーマンス向上）
