### ISSUE TITLE
GitHub ActionsでApp Runnerデプロイ後にCloudFrontキャッシュを自動削除する機能を追加

### ISSUE THREAD

**Issue by ryota-09** [ryota-09/ryota-blog#89]
## 概要
App RunnerのデプロイがRunning状態になってからCloudFrontのキャッシュを削除するGitHub Actionsワークフローを作成する必要があります。

## 要件
- App Runnerのデプロイ完了を待機
- デプロイ完了後にCloudFrontキャッシュを削除
- エラーハンドリングとログ出力

## 実装内容
以下のワークフローを `.github/workflows/deploy.yml` に実装：

```yaml
name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t \$ECR_REGISTRY/\$ECR_REPOSITORY:\$IMAGE_TAG .
          docker push \$ECR_REGISTRY/\$ECR_REPOSITORY:\$IMAGE_TAG
        env:
          ECR_REGISTRY: \${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ryota-blog
          IMAGE_TAG: \${{ github.sha }}

      - name: Wait for App Runner deployment
        run: |
          SERVICE_ARN=\"arn:aws:apprunner:ap-northeast-1:\${{ secrets.AWS_ACCOUNT_ID }}:service/ryota-blog/your-service-id\"
          
          echo \"Waiting for App Runner deployment to complete...\"
          aws apprunner wait service-updated --service-arn \$SERVICE_ARN
          
          aws apprunner describe-service --service-arn \$SERVICE_ARN --query 'Service.Status'

      - name: Invalidate CloudFront cache
        run: |
          DISTRIBUTION_ID=\"\${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}\"
          
          echo \"Creating CloudFront invalidation...\"
          INVALIDATION_ID=\$(aws cloudfront create-invalidation \\
            --distribution-id \$DISTRIBUTION_ID \\
            --paths \"/*\" \\
            --query 'Invalidation.Id' \\
            --output text)
          
          echo \"Invalidation ID: \$INVALIDATION_ID\"
          
          echo \"Waiting for invalidation to complete...\"
          aws cloudfront wait invalidation-completed \\
            --distribution-id \$DISTRIBUTION_ID \\
            --id \$INVALIDATION_ID
          
          echo \"CloudFront cache invalidation completed\!\"
```

### GitHub Secrets
- \`AWS_ROLE_ARN\`: OIDC用のIAMロールARN
- \`AWS_ACCOUNT_ID\`: AWSアカウントID  
- \`CLOUDFRONT_DISTRIBUTION_ID\`: CloudFrontのディストリビューションID

### IAM権限
```json
{
  \"Version\": \"2012-10-17\",
  \"Statement\": [
    {
      \"Effect\": \"Allow\",
      \"Action\": [
        \"apprunner:DescribeService\",
        \"cloudfront:CreateInvalidation\",
        \"cloudfront:GetInvalidation\"
      ],
      \"Resource\": \"*\"
    }
  ]
}
```

## タスク
- [ ] ワークフローファイルの作成
- [ ] GitHub Secretsの設定
- [ ] IAMロール権限の確認・更新
- [ ] デプロイテストの実行
